require("dotenv").config();
const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const { OAuth2Client } = require("google-auth-library");
const OpenAI = require("openai");
const { createClient } = require("@supabase/supabase-js");

const app = express();

// ==============================
// 🔐 CONFIG
// ==============================
const CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
  });

  const supabase = createClient(
    process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_KEY
      );

      const client = new OAuth2Client(CLIENT_ID);

      // ==============================
      // ✅ MIDDLEWARE
      // ==============================
      app.use(cors());
      app.use(bodyParser.json());

      // ==============================
      // 🧠 COACH PERSONALITY
      // ==============================
      const COACH = `
      You are a high-performance personal growth coach.

      - Short, sharp, powerful
      - Mix discipline + motivation
      - Never long paragraphs

      Push when strong
      Support when low
      Call out excuses
      `;

      // ==============================
      // 🔐 VERIFY USER
      // ==============================
      async function verifyUser(req) {
        const token = req.headers.authorization?.split(" ")[1];
          if (!token) throw new Error("No token");

            const ticket = await client.verifyIdToken({
                idToken: token,
                    audience: CLIENT_ID,
                      });

                        return ticket.getPayload();
                        }

                        // ==============================
                        // 🔥 XP + LEVEL SYSTEM
                        // ==============================
                        function calculateLevel(xp) {
                          return Math.floor(xp / 100) + 1;
                          }

                          function getProgress(xp) {
                            return xp % 100;
                            }

                            function updateProgress(user) {
                              const today = new Date().toDateString();
                                const last = user.lastActiveDate
                                    ? new Date(user.lastActiveDate).toDateString()
                                        : null;

                                          let streak = user.streak || 0;
                                            let xp = user.xp || 0;

                                              if (last === today) {
                                                  xp += 10;
                                                    } else {
                                                        const yesterday = new Date();
                                                            yesterday.setDate(yesterday.getDate() - 1);

                                                                if (last === yesterday.toDateString()) {
                                                                      streak += 1;
                                                                          } else {
                                                                                streak = 1;
                                                                                    }

                                                                                        xp += 10;
                                                                                          }

                                                                                            return {
                                                                                                streak,
                                                                                                    xp,
                                                                                                        level: calculateLevel(xp),
                                                                                                            levelProgress: getProgress(xp),
                                                                                                                lastActiveDate: new Date(),
                                                                                                                  };
                                                                                                                  }

                                                                                                                  // ==============================
                                                                                                                  // 🧠 MEMORY BUILDER
                                                                                                                  // ==============================
                                                                                                                  function buildMemory(user) {
                                                                                                                    const last = user.reflections.slice(-5);

                                                                                                                      return `
                                                                                                                      User: ${user.name}
                                                                                                                      Streak: ${user.streak}
                                                                                                                      XP: ${user.xp}

                                                                                                                      Habits:
                                                                                                                      ${JSON.stringify(user.habits)}

                                                                                                                      Reflections:
                                                                                                                      ${last.map(r => "- " + r.text).join("\n")}
                                                                                                                      `;
                                                                                                                      }

                                                                                                                      // ==============================
                                                                                                                      // 🧠 MOOD
                                                                                                                      // ==============================
                                                                                                                      function moodInstruction(user) {
                                                                                                                        const last = user.reflections.slice(-1)[0];
                                                                                                                          if (!last) return "";

                                                                                                                            switch (last.mood) {
                                                                                                                                case "stressed": return "User stressed → calm tone";
                                                                                                                                    case "low": return "User low → supportive";
                                                                                                                                        case "happy": return "User strong → push harder";
                                                                                                                                            default: return "";
                                                                                                                                              }
                                                                                                                                              }

                                                                                                                                              // ==============================
                                                                                                                                              // 🎯 TEST
                                                                                                                                              // ==============================
                                                                                                                                              app.get("/", (req, res) => {
                                                                                                                                                res.send("Final Backend Running 🚀");
                                                                                                                                                });

                                                                                                                                                // ==============================
                                                                                                                                                // 🔐 LOGIN
                                                                                                                                                // ==============================
                                                                                                                                                app.post("/google-login", async (req, res) => {
                                                                                                                                                  try {
                                                                                                                                                      const { token } = req.body;

                                                                                                                                                          const ticket = await client.verifyIdToken({
                                                                                                                                                                idToken: token,
                                                                                                                                                                      audience: CLIENT_ID,
                                                                                                                                                                          });

                                                                                                                                                                              const payload = ticket.getPayload();

                                                                                                                                                                                  const { data: user } = await supabase
                                                                                                                                                                                        .from("users")
                                                                                                                                                                                              .select("*")
                                                                                                                                                                                                    .eq("email", payload.email)
                                                                                                                                                                                                          .single();

                                                                                                                                                                                                              if (!user) {
                                                                                                                                                                                                                    await supabase.from("users").insert({
                                                                                                                                                                                                                            email: payload.email,
                                                                                                                                                                                                                                    name: payload.name,
                                                                                                                                                                                                                                            xp: 0,
                                                                                                                                                                                                                                                    streak: 0,
                                                                                                                                                                                                                                                            level: 1,
                                                                                                                                                                                                                                                                    levelProgress: 0,
                                                                                                                                                                                                                                                                            habits: [],
                                                                                                                                                                                                                                                                                    reflections: [],
                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                  res.json({ success: true });

                                                                                                                                                                                                                                                                                                    } catch {
                                                                                                                                                                                                                                                                                                        res.json({ success: false });
                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                          // ==============================
                                                                                                                                                                                                                                                                                                          // 📥 GET USER
                                                                                                                                                                                                                                                                                                          // ==============================
                                                                                                                                                                                                                                                                                                          app.get("/user", async (req, res) => {
                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                const payload = await verifyUser(req);

                                                                                                                                                                                                                                                                                                                    const { data } = await supabase
                                                                                                                                                                                                                                                                                                                          .from("users")
                                                                                                                                                                                                                                                                                                                                .select("*")
                                                                                                                                                                                                                                                                                                                                      .eq("email", payload.email)
                                                                                                                                                                                                                                                                                                                                            .single();

                                                                                                                                                                                                                                                                                                                                                res.json({ success: true, user: data });

                                                                                                                                                                                                                                                                                                                                                  } catch {
                                                                                                                                                                                                                                                                                                                                                      res.json({ success: false });
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                        // ==============================
                                                                                                                                                                                                                                                                                                                                                        // 📝 SAVE HABITS
                                                                                                                                                                                                                                                                                                                                                        // ==============================
                                                                                                                                                                                                                                                                                                                                                        app.post("/save-habits", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                              const payload = await verifyUser(req);
                                                                                                                                                                                                                                                                                                                                                                  const { habits } = req.body;

                                                                                                                                                                                                                                                                                                                                                                      const { data: user } = await supabase
                                                                                                                                                                                                                                                                                                                                                                            .from("users")
                                                                                                                                                                                                                                                                                                                                                                                  .select("*")
                                                                                                                                                                                                                                                                                                                                                                                        .eq("email", payload.email)
                                                                                                                                                                                                                                                                                                                                                                                              .single();

                                                                                                                                                                                                                                                                                                                                                                                                  const updates = updateProgress(user);

                                                                                                                                                                                                                                                                                                                                                                                                      await supabase
                                                                                                                                                                                                                                                                                                                                                                                                            .from("users")
                                                                                                                                                                                                                                                                                                                                                                                                                  .update({
                                                                                                                                                                                                                                                                                                                                                                                                                          habits,
                                                                                                                                                                                                                                                                                                                                                                                                                                  ...updates,
                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq("email", payload.email);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.json({ success: true, ...updates });

                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ success: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 🧠 REFLECTION + AI
                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                          app.post("/save-reflection", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const payload = await verifyUser(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { text } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data: user } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .from("users")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .select("*")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eq("email", payload.email)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const memory = buildMemory(user);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ai = await openai.chat.completions.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              model: "gpt-4o-mini",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { role: "system", content: COACH },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              role: "user",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        content: `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${memory}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Analyze:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "${text}"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Return JSON:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { mood, insight, advice }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const parsed = JSON.parse(ai.choices[0].message.content);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const updated = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...user.reflections,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { text, ...parsed, date: new Date() }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from("users")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .update({ reflections: updated })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq("email", payload.email);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ success: true, ai: parsed });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.json({ success: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 💬 CHAT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.post("/chat", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const payload = await verifyUser(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { message } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { data: user } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from("users")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .select("*")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq("email", payload.email)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const memory = buildMemory(user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const mood = moodInstruction(user);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const ai = await openai.chat.completions.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                model: "gpt-4o-mini",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      messages: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { role: "system", content: COACH + mood },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                role: "user",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          content: `${memory}\nUser: ${message}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reply: ai.choices[0].message.content
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.json({ success: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🚀 START
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("🚀 Backend running on", PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });